# Generated by Django 5.2.7 on 2025-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=120)),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("github", models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
